### PR TITLE
deprecation proposal

### PR DESCRIPTION
**Pull request by bamarni**
Hello :)

I had been working on a similar completion tool some time ago, that I've completely rewritten lately (https://github.com/bamarni/symfony-console-autocomplete).

It comes with various improvements compared to this one (no php code, doesn't touch COMP_WORDBREAKS directly, etc.) and also allows to dump a static completion file for a given tool, instead of inspecting it on the fly, which is slower.

As I saw that this one is unmaintained, I'm proposing to deprecate it for mine, what do you think?

### CODE REVIEW

**Comment by weaverryan** [comment]
I'm using this currently locally (I've been chatting with Bilal about it) and it seems to work really nicely. I'm taking the lazy installation approach where I just require the library via composer globally and add 1 line to my `.base_profile`. It also auto-completes options if you type `--` and then hit tab.

I'm :+1: for this idea. Ping @cursedcoder @akovalyov you guys are 2 other Knp'ers who have actually had commits to this and I wonder what you think.

**Comment by cursedcoder** [comment]
:+1:

**Comment by weaverryan** [comment]
Thanks @bamarni! I've still been using your autocomplete locally without any issues :)

**Comment by bamarni** [comment]
@weaverryan glad to hear this ;)

**Pull request merged**
